### ISSUE TITLE
Allow for a custom starting directory

### ISSUE THREAD

**Issue by polprog** [malxau/yori#104]
I really like Yori and I've switched to it on all my Windows machines. It gives me a very unix like experience to which im used to.
However Yori starts in `C:\Windows\System32` as the default working directory. I usually want to operate on files in my user profile directory (`C:\Users\foo..`). Typing `cd ~` takes a while especially since on some layouts the tilde is used as Alt-Gr and to get an actual tilde one needs to press the key combo twice.

I propose a couple ways to solve this:

* Add an environment variable for the default working dir for Yori
* Add an alias, `cd` does `cd ~`
* Make Yori start in  `%userprofile%` by default

What do you think?

**Comment by malxau** [comment]
How is Yori being launched in this scenario?

Normally Yori keeps the current directory of the parent process.  When launched from Explorer, the starting directory is specified in the shortcut properties.  For the shortcut in the start menu, this could be changed with `scut -modify ~Programs\Yori.lnk -workingdir c:\` .

**Comment by polprog** [comment]
Ah, this is probably it. It's launched from the start menu, I will test if changing that works
