### ISSUE TITLE
"cab.exe -s -u" does not overwrite files with read-only and system attributes set

### ISSUE THREAD

**Issue by aleaksunder** [malxau/yori#115]
Hi!

The thing is that if you have files with these attributes within .cab-archive you can not simply uncompress it over the existing files with such attributes.

**Comment by malxau** [comment]
This should be fixed with commit 50f72e0dc41a1d2fa5a1d332eb40492efbf98862 .  Let me know if you have further issues in this area.

**Comment by aleaksunder** [comment]
Cool! Thanks! Gratz with 2.0 release!
