### ISSUE TITLE
fail to install yori-core on amd

### ISSUE THREAD

**Issue by diagrammatics** [malxau/yori#120]
using the installer downloaded from http://www.malsmith.net/yori/

 Fails on installer step 2 of 5 with message:
 
 Failed to install yori-core from http:/www.malsmith.net/download/?obj=yori/latest-stable/yori-core-amd64.cab

**Comment by malxau** [comment]
Is this behavior consistent for you?

 

I tried this now and it worked for me.  My guesses would be:

1.       Transient load overwhelming the server causing it to be unable to serve requests (trying again will fix it);

2.       A virus scanner that heuristically believes the payload might be malicious and is blocking it.

 

I added the URL to VirusTotal which was able to re-read the payload, and none of the scanners there are currently flagging it.

**Comment by diagrammatics** [comment]
Yes, trying again a bit later worked.
