### ISSUE TITLE
ConEmu + Clink + Yori + Python + xonsh = surprise XD

### ISSUE THREAD

**Issue by aleaksunder** [malxau/yori#121]
Hi!

This is not an issue and all of was not on purpose but happened by accident :D I was bundling Python distro with some stuff and suddenly many pieces pieces came together in something maybe weird but at least I've decided to share this with somebody who will this interesting...

Well long story short:

![screenshot](https://github.com/malxau/yori/assets/40979373/014acdbf-f579-4180-bf8f-e8c3170da7cf)

The simplest way to get it is to install: `cmder` + `yori` + `Python`

I know this is weird XD But look what you can get with it:
- linux aliases via Clink like `ls -l`
- full access to all Yori's power and utilities but you need to type commands as it's filenames like: `yecho`
- full acesss to xonsh and all that Python stuff like like 'pywin32' and objects and ranges and so on
- this stuff can work on Windows XP i believe :D At least i've managed to install 'xonsh' on Python v3.4.4 with this:
```
pip install xonsh==0.8.12
pip install pygments
pip install prompt-toolkit
pip install setproctitle-1.1.10-cp34-cp34m-win_amd64.whl
```
the latest is actually a file, you need to get it manually.

It's a bit buggy for now so i've noticed sometime up/down/left/right buttons stops working and comes back to work after 'xonsh' restart and I believe `Clink` is to blame but you can use this stuff without `Clink` and `ConEmu`.
Really no one expected some "magic" will happen or this is somehow possible but this is interesting... and it works!
So I bet someone will find this fun at least :) And btw what do you think about the idea to embeed Python as additional scripting language for plugins maybe? :D

Well IDK really just want to share this XD Happy Holidays!

**Comment by fluentmoheshwar** [comment]
bruh :V

**Comment by aleaksunder** [comment]
Come on :D That was for ideas maybe...

Anyway imho we don't need another shell that can do the same thing we already have working flawlessly. And btw `cmd` + `yori` doing their job perfectly if you experienced in `cmd`. Ok I will not say for everyone but for me as for developer the only thing I'm missing in `cmd ` and `yori` is _functions_ with parameters and so on...

The thing about `xonsh` is it implemented in Python. So idk but almost everybody doing the same way: they take interpreter like `python` or `nodejs` or `csharpscript` and building their shells in it.

But why not take the native shell like `yori` and place the interpreter in it.
So the idea is very simple: why not take native perfect working scripting engine like `LuaScript` or `python` or no matter what it will be... but we can have scripting experience using known tech and not just `yet another shell`

**Comment by aleaksunder** [comment]
Anyway im
