### ISSUE TITLE
feature request: DIR /W multi-column filename-only view

### ISSUE THREAD

**Issue by boeckmann** [malxau/yori#123]
I regularly use the DIR /W option of TCC/LE (CMD.EXE has it also, and also COMMAND.COM). DIR /W shows only the filenames, but in multiple columns. It would be really nice to have this in Yori too.

**Comment by malxau** [comment]
Have you tried sdir?  It was really a precursor to Yori – multi-column seems great for interactive use, not scripting, so it made sense to make something very approachable for interactive scenarios.

 

Sdir ended up being absurdly customizable too: http://www.malsmith.net/sdir/

**Comment by boeckmann** [comment]
Sorry, I missed the SDIR command, I'm sure it will fit my need. Thank you for providing Yori. This is really a great piece of software! Perhaps you may consider to at least add the commands unique to Yori to the guide on the website, so users new to the software may discover them more easily.
