### ISSUE TITLE
Check 4NT / TCC docs for ideas

### ISSUE THREAD

**Issue by mixmastamyk** [malxau/yori#15]
Nice work, definitely a need for a shell between cmd and powershell in complexity.  Just by implementing Ctrl-L you've given me a reason to use and promote it!

Many years ago before moving to Unix I used the 4NT shell.  It was ten times better than cmd and still is.  It's a great example of how to improve on cmd and keep it compatible shell.  I lost track of it but I bet the docs are somewhere.

Fish is another great user-friendly shell.

Feel free to close as this is just a comment post.

**Comment by malxau** [comment]
I do look around at what other shells are doing periodically.  Let me know if there's a good feature that TCC has which I'm missing.
