### ISSUE TITLE
Implement Ctrl+Z and/or Ctrl+D to exit shell

### ISSUE THREAD

**Issue by mixmastamyk** [malxau/yori#17]
Would be nice to implement hot keys to exit the shell as POSIX shells do.  Traditionally it is ^D, though Windows used ^Z+Enter instead.  

However since WSL has become more common implementing both might be a good idea.  Thanks.

**Comment by malxau** [comment]
I hadn't heard of this before.  I see that ^D will immediately terminate bash, but I don't see ^Z working for either CMD or Powershell.  Does this require any specific configuration/environment/version?

**Comment by mixmastamyk** [comment]
Doesn't look like it exits the Windows shells, but it will exit some Windows console programs.  Python repl is one, and I think there are many others.  Perhaps COPY CON ... or stdin redirection but the names escape me at the moment.  I bet google would know a few examples.  I'm taking off now or I'd look.  Maybe in a few days.

**Comment by malxau** [comment]
^Z is used to terminate the input stream when using things like copy con - it acts as an EOF marker.  But that seems very different to terminating the shell process.  Right now I can see an argument for implementing ^D but I don't think it would make much sense to use ^Z if if it's not used for this purpose elsewhere.

**Comment by mixmastamyk** [comment]
Yes, when you terminate the input stream of a traditional shell, it logically exits.  I didn't realize cmd.exe et al didn't do that but have used it regularly with Python for Windows, etc.  

Maybe it is another poor design decision on part of cmd designers, never occurred to them, or maybe they thought it was a bit too accident prone.  Guess it is up to you what you'd like to do.

**Comment by malxau** [comment]
Hmm, that's an interesting perspective.  I guess back in the TTY days that makes a lot of sense.  In a readline world though, these keys are processed explicitly by the shell.  Ctrl+D on bash inserts the "exit" command and executes it, but only if the user has not typed anything into the line input buffer.  This can be observed by launching a child instance and hitting Ctrl+D (so the display is still there.)

I made a change to Yori to handle Ctrl+D in the same way and pushed it to master.

**Comment by mixmastamyk** [comment]
Cool, thanks.

**Comment by malxau** [comment]
1.20 is released including this change.  Let me know if there are any issues.

**Comment by mixmastamyk** [comment]
It works, woot!
