### ISSUE TITLE
Question: Customize display of path in prompt

### ISSUE THREAD

**Issue by cbrit** [malxau/yori#26]
Is there any mechanism for changing how paths are displayed in the prompt? For example,

```[TimeStamp] source>``` 
instead of 
```C:\Users\Name\source>``` or something similar.

**Comment by malxau** [comment]
Prompts in Yori can be generated by the output of a process, so they're not limited to predefined formats provided by the shell.  See http://www.malsmith.net/yori/guide/#env_yoriprompt .

This often requires use of escape characters to ensure that symbols including backquotes and quotes are preserved into the variable, as opposed to being interpreted by the command setting the variable.

A prompt like the one you're suggesting could be achieved with something like:
```
set YORIPROMPT=^`finfo -d -f ^"[$CREATEDATE_YEAR$/$CREATEDATE_MON$/$CREATEDATE_DAY$] $NAME$^" .^`$G_OR_ADMIN_G$
```

**Comment by cbrit** [comment]
Thanks @malxau. When I set that value in my account environment variables it does not seem to take effect. `set` shows the variable is there though:

 
![image](https://user-images.githubusercontent.com/23322838/75161354-42688d80-56e1-11ea-9549-2ad0c110dbda.png)

![image](https://user-images.githubusercontent.com/23322838/75161557-9bd0bc80-56e1-11ea-91e3-1333823ba2c4.png)

**Comment by malxau** [comment]
This variable is over-escaped.  Remove all of the ^'s - I included those to show how to set the variable from the command line.  Setting it directly in the UI means all of the special characters will be included without escaping.

**Comment by cbrit** [comment]
That fixed it. Thank you!
