### ISSUE TITLE
Have auto-complete add backslash after folder name

### ISSUE THREAD

**Issue by flipswitchingmonkey** [malxau/yori#27]
Currently when autocompleting a directory  Yori will auto-complete the folder name, but then to continue I have to manually type in a backslash to then complete further down the tree. It'd be nice if a second <tab> would add the backslash automatically.

**Comment by malxau** [comment]
This behavior is optional in 1.20.  See http://www.malsmith.net/yori/guide/#env_yoricompletewithtrailingslash
