### ISSUE TITLE
Incorrect value of %CD% while executing batch script

### ISSUE THREAD

**Issue by AugustIgner** [malxau/yori#28]
A batch script I'm running keeps failing because %CD% does not seem to be up to date.

**Comment by malxau** [comment]
Can you please provide more details, preferably including the relevant portions of the script that can be used to reproduce the problem? Also, what is the file extension of the script?

I've been trying with:
```
echo %CD%
pushd ..
echo %CD%
popd
```
Which appears to work correctly both for .cmd and .ys1 scripts.

**Comment by AugustIgner** [comment]
> 
> 
> Can you please provide more details, preferably including the relevant portions of the script that can be used to reproduce the problem? Also, what is the file extension of the script?
> 
> I've been trying with:
> 
> ```
> echo %CD%
> pushd ..
> echo %CD%
> popd
> ```
> 
> Which appears to work correctly both for .cmd and .ys1 scripts.

Sorry I had an AutoRun script in cmd registry which would cd to a default directory. I had completely forgotten about it.
