### ISSUE TITLE
Process exits and yori freezes when using with Windows Terminal

### ISSUE THREAD

**Issue by igitur** [malxau/yori#29]
Hi,

So I followed the [instructions](https://www.hanselman.com/blog/YoriTheQuietLittleCMDReplacementThatYouNeedToInstallNOW.aspx) by Scott Hanselman to install Yori and use it with Windows Terminal.

For the most part, it works great, but every now and then, when I hit Ctrl-C to kill a process, yori also freezes up. For example, simply hitting Ctrl-C while pinging something:
![image](https://user-images.githubusercontent.com/145854/77068955-2d390300-69f0-11ea-8a6f-9057264f25ab.png)

I don't have this problem with Yori's own terminal, just when I use Windows Terminal. Maybe this is not a Yori issue, but rather a Windows Terminal, but I don't experience it with any of the other shells that I also use in Windows Terminal, e.g. PowerShell or msys2.

**Comment by malxau** [comment]
Can I ask which version of Windows Terminal you have, and which version of Yori you have?  I've been trying to reproduce this, so far without success.

What I've tried:
- With WT 0.10.761.0 and 0.9.433.0
- With Yori 1.20 and the current testing build
- Copied Scott's profile.  (I had to remove the color scheme, but that seems unlikely to be related)
- Ran ping and hit both Ctrl+C and Ctrl+Break

I haven't been able to observe this behavior at all.  Can you think of anything else that I can try?

One challenging case in Yori that may be related but I don't see it doing quite the same thing is nested shells.  Yori first asks child processes nicely to die, and if they don't, it's willing to terminate them.  This is frequently nice from a user's point of view, but when nested instances are present it can end up killing a child instance.  But getting the output you showed here would require a parent instance that launches a child instance for interactive use and the parent will terminate as soon as the child terminates (ie., `yori /c yori` type thing.)

**Comment by igitur** [comment]
Ah, yes, it was a nested instance, but not deliberately. I had installed yori via the scoop package manager, which executes yori via a shim layer. I now changed my Windows Terminal to execute the underlying `yori.exe` directly and that solves my problem. Thanks so much.
