### ISSUE TITLE
Add Nested Aliases

### ISSUE THREAD

**Issue by Skibicki** [malxau/yori#3]
Nested Aliases are a feature I would like to have in Yori. I am using this feature in TCC/LE and I'm not sure if this can be done in Yori. TCC/LE is discontinued so I started looking for alternatives with aliases. My goals is to use an alias within another alias.

Example:
yd=youtube-dl
ydf=yd --format

From the Take Command manual:

> alias wp = e:\winword\winword.exe
> 
> alias w = `pushd c:\wp & wp & popd`
> 
> The second alias above could have included the full path and name of WINWORD.EXE instead of calling the WP alias. However, writing two aliases makes the second one easier to read and understand, and makes the first alias available for independent use. If you rename the WINWORD.EXE program or move it to a new directory, only the first alias needs to be changed.

The aliases below report "unrecognized command"
ydf="yd --format" $1$
ydf ="yd --format $1$"

> c:\>ydf 22 https://youtube.com/watch?v=ObgqvKJR1r8
Unrecognized command: yd --format 22

**Comment by malxau** [comment]
> yd=youtube-dl
> ydf=yd --format

That should be fine.

> alias w = pushd c:\wp & wp & popd

This will not currently work in Yori.  "w" expands to a single command, not a compound expression.

>> If you rename the WINWORD.EXE program or move it to a new directory, only the first alias needs to be changed.

This is different between the two.  In Yori the second alias is expanded at the time it is defined, so changing the first will do nothing.  Doing this means the shell doesn't need to recursively attempt to resolve the alias, or handle loops in resolution, etc.

> The aliases below report "unrecognized command"
> ydf="yd --format" $1$
> ydf ="yd --format $1$"

This is occurring because of the quotes.  It's expanding this into a single command, so is looking for a file called "yd --format.exe" or similar.  If you omit the quotes, this should work fine.

**Comment by Skibicki** [comment]
I don't know command line basics so this may look strange.

> > yd=youtube-dl
> > ydf=yd --format
> 
> That should be fine.

It's not saving '--format'

> c:\>alias yd=youtube-dl
> c:\>alias ydf=yd --format
> c:\>alias
> yd=youtube-dl
> ydf=youtube-dl

> c:\>alias ydf=yd --format $1$
> c:\>alias
> yd=youtube-dl
> ydf=youtube-dl

> c:\>alias ydf=yd --format $1$ $2$
> c:\>alias
> yd=youtube-dl
> ydf=youtube-dl

It fails with combined aliases but works with complete commands.

ydf=youtube-dl --format $1$ $2$
> c:\>ydf 22 https://youtube.com/watch?v=ObgqvKJR1r8
> [youtube] ObgqvKJR1r8: Downloading webpage

**Comment by malxau** [comment]
> It's not saving '--format'
```
c:>alias yd=youtube-dl
c:>alias ydf=yd --format
c:>alias
yd=youtube-dl
ydf=youtube-dl
```
I'm sorry, I misunderstood.  In this case "yd" is defined as "youtube-dl" without specifying what to do with any arguments, so it's discarding them all.  I think you want:
```
c:>alias yd=youtube-dl $*$
c:>alias ydf=youtube-dl --format $*$
c:>alias
yd=youtube-dl $*$
ydf=youtube-dl --format $*$
```

**Comment by Skibicki** [comment]
Thank you.
Those aliases worked without any problems.
