### ISSUE TITLE
FTYPE and ASSOC builtin commands

### ISSUE THREAD

**Issue by rksouthee** [malxau/yori#30]
I had an occasion to set up a filetype associated with an executable in the prompt, and would normally use the FTYPE and ASSOC commands in CMD.

I was wondering if these internal commands should be added to yori. This has been the only occasion in which I've found this command necessary, but may be useful to other users, particularly those that have come from CMD.

**Comment by malxau** [comment]
Thanks for letting me know.  I always thought these commands were external, and obviously don't make much use of them.  I pushed an initial version of assoc which has a switch to behave like ftype and an alias for both.

CMD's version of these seems to operate on the system registry only (not the user registry.)  This seemed a little...strange.  I added some switches in there so they can display and manipulate both.

That said, since I don't use these, I'd appreciate it if you try them out and give me any feedback.

**Comment by rksouthee** [comment]
I have an issue when trying to execute a python script.

The following is when using cmd.exe

```
cmd>type hello.py
import time

print("Hello, World")
time.sleep(3)

cmd>set pathext
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.PY

cmd>assoc .py
.py=Python.File

cmd>ftype python.file
python.file="C:\WINDOWS\py.exe" "%L" %*

cmd>hello
Hello, World
```

which is the output I would expect. When using yori and executing `hello` a new console window is created where the message is printed.

```
yori>type hello.py
import time

print("Hello, World")
time.sleep(3)
yori>set pathext
PATHEXT=.YS1;.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.PY
yori>assoc .py
.py=Python.File
yori>assoc -t python.file
python.file="C:\WINDOWS\py.exe" "%L" %*
yori>hello
yori>C:\Windows\py.exe hello.py
Hello, World
```

**Comment by malxau** [comment]
Well, that's the second new thing I learned in this issue.  I pushed a change to master which reuses the same console window in this case.  I haven't tested it much though.

**Comment by rksouthee** [comment]
Thank you for fixing that issue. Unfortunately I'm unable to delete or update associations:

```
yori>assoc .txt=
Error occurred while processing: .txt.

yori>assoc .txt=txtfile
Error occurred while processing: .txt.

yori>assoc -t txtfile=
Error occurred while processing: txtfile.

yori>assoc -t txtfile=%SystemRoot%\system32\NOTEPAD.EXE %1
Error occurred while processing: txtfile.
```

I'm sorry, I didn't check these operations last time since I had set them up already.

**Comment by malxau** [comment]
Clearly I should fix the error message; I think that was patterned on what CMD does but it seems very unhelpful.  Just asking the obvious though, was this from an elevated prompt?  CMD modifies the system hive, so I made that the default, which will fail if it's not elevated.

**Comment by rksouthee** [comment]
I did not use an elevated prompt. I realised after and should have tested using the user registry. I tested with an elevated prompt and it worked as expected. I also checked using a non-elevated prompt using the user registry and everything works so far.

Thank you for your help with this issue.
