### ISSUE TITLE
Yori portablity

### ISSUE THREAD

**Issue by aleaksunder** [malxau/yori#31]
Hello!

This is such a fantastic work I have been spending years to find! Thank you so much!!!
I have just found it and noticed one thing that may affect portability and independece of each Yori distributive.

By default Yori at startup executes user scripts by this code in `sh\main.c`
`
    YoriLibConstantString(&RelativeYoriInitName, _T("~\\YoriInit.d\\*"));
    YoriLibForEachFile(&RelativeYoriInitName, YORILIB_FILEENUM_RETURN_FILES, 0, YoriShExecuteYoriInit, NULL, NULL);
    YoriLibConstantString(&RelativeYoriInitName, _T("~\\YoriInit*"));
    YoriLibForEachFile(&RelativeYoriInitName, YORILIB_FILEENUM_RETURN_FILES, 0, YoriShExecuteYoriInit, NULL, NULL);
`

So in situation when I for example just want to run independent copy of Yori which would only do what I want and nothing more Yori will launch current User Scripts at startup, which can modify environment or maybe be compromised by any malware.

Just want to ask, is there a way to disable this behavior maybe by some command line options and if it can not be disabled I would prefer to remove those lines from original source, since this behavior can be easily achived with commands to execute "~\YoriInit" in files which is in "~AppDir\YoriInit"

**Comment by malxau** [comment]
Fair enough, I'll add an option to disable user scripts (while continuing to execute system scripts.)

As far as removing the code in the original source, see issue #4 .  This isn't a feature I was ever really a fan of, but I'm trying to run the project in a way that's responsive to user requests, which gets challenging when users disagree :)

**Comment by aleaksunder** [comment]
That's nice to hear... IMHO all kind of stuff that makes your software dependent on any user stuff without providing an option to turn that on/off by command line switch or maybe ini-file parameter, ie locale settings, registry settings, %appdata% files etc. ) brings portability and reliability to almost nothing, since nobody really can be assured that software will behave as conceived!

I will close an issue... Will write if I found something! I am totally excited of your project, thanks for providing us such a masterpiece of compatibiliy ) Finally found someone being able to fix all that cmd stuff and without providing 200+ Mb new shell )) Huge thanks for all your hard work!!!
