### ISSUE TITLE
Persisent history

### ISSUE THREAD

**Issue by muv1** [malxau/yori#35]
I currently use Cygwin, and the history is saved via `.bash_history`. This means that if you close the shell and reopen, you can still access the history.

Does Yori have an option for this?

**Comment by malxau** [comment]
Yes.  I tried to follow bash as closely as possible.  As far as I know, bash uses $HISTFILE, $HISTFILESIZE, and $HISTSIZE for this.  Yori uses equivalent %YORIHISTFILE% and %YORIHISTSIZE%.  See http://www.malsmith.net/yori/guide/#env_yorihistfile .

**Comment by muv1** [comment]
Thank you
