### ISSUE TITLE
Less

### ISSUE THREAD

**Issue by muv1** [malxau/yori#40]
Does Yori offer a pager? I am looking to replace Cygwin, but it includes Less:

https://en.wikipedia.org/wiki/Less_(Unix)

**Comment by muv1** [comment]
Workaround:

<https://github.com/tigrawap/slit>

**Comment by malxau** [comment]
Yori includes ymore.exe, aliased to "more", which includes scrolling, search, asynchronous population, and other common features that less is used for.  Like everything else, this can be used from within the Yori shell or standalone as a replacement for the inbox more.com.

**Comment by muv1** [comment]
Found it, thanks:

<http://malsmith.net/download?obj=yori/latest-stable/yori-typical-amd64.cab>
