### ISSUE TITLE
timethis with no arguments

### ISSUE THREAD

**Issue by rksouthee** [malxau/yori#54]
When running `timethis` without any arguments the program is crashing. After running the program the error level is 3221225477, printing that using `err` gives "The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s".
I would have expected the output to be "timethis: missing argument".

More information:
```sh
Desktop>ver
YoriLib version: 01.30
Yori shell version: 01.30
Build date: Jul 18 2020
Desktop>timethis
Desktop>echo %errorlevel%
3221225477
Desktop>err 3221225477
The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
Desktop>
```

Quickly looking at the source for timethis.c I think this is an issue with `StartArg` since you check for missing argument when `StartArg` is zero but it doesn't look like `StartArg` can be 0.

**Comment by pyproman** [comment]
Looks like this bug is only in modular `timethis` (not `timethis.exe`). `timethis.exe` ends with `timethis: unable to find executable`.
