### ISSUE TITLE
Allow the shell to recognize Ctrl+[ as Escape

### ISSUE THREAD

**Issue by rksouthee** [malxau/yori#59]
From using vim rather than pressing the Escape key I use the Ctrl+[ combination instead. Since the combination isn't being used for anything in the Yori shell, I thought it would be a nice addition.

On an unrelated note, I'm not sure if it's better that I open an issue or just send a pull request for features, do you have any preferences?

**Comment by pyproman** [comment]
There was an combination for ESC: <kbd>Ctrl</kbd>+<kbd>E</kbd>. It was deleted in #1. As a workaround, you can hold <kbd>Alt</kbd> and type `027` *.
Also, to make colors without remembering ANSI escape codes, try out `color`**: ![echo `color red`Red`color reset`](https://user-images.githubusercontent.com/45491635/95651420-fa24a100-0af2-11eb-8241-08b6ec411466.png "echo `color red`Red`color reset`")
###### * Does not work in EDIT.
###### ** ![All colors](https://user-images.githubusercontent.com/45491635/95651616-491f0600-0af4-11eb-9d93-777cfe258077.png "Screenshot of second page of sdir -filecolor on Windows 10 with color scheme Material Dark"), `invert`: invert

P.S. Here are lines that are handling <kbd>Ctrl</kbd> key combinations in both shell and libwin(multiline editor):
[sh/input.c lines 2170-2255](https://github.com/malxau/yori/blob/master/sh/input.c#L2170-L2255)
[libwin/edit.c lines 1157-1176](https://github.com/malxau/yori/blob/master/libwin/edit.c#L1157-L1176)

**Comment by malxau** [comment]
To be clear though, in Vim Ctrl+[ means the escape key, not the escape character, correct?

As far as whether to file issues or pull requests, I don't mind either way.  Things like this are easy for anyone to implement, so it's not a big tax on my time but if people want to contribute directly that's fine by me too.  The only thing I'd ask, which so far hasn't come up, is to talk first before starting on larger changes to maximize the chance that they are handling all of the right cases and can be merged cleanly.

**Comment by rksouthee** [comment]
Sorry for the confusion, I was referring to the Escape key, that is rather than pressing `Esc` and clearing the line, I could instead press `Ctrl+[` to accomplish the same thing.

**Comment by pyproman** [comment]
> Sorry for the confusion, I was referring to the Escape key, that is rather than pressing `Esc` and clearing the line, I could instead press `Ctrl+[` to accomplish the same thing.

Oh. In CMD, <kbd>Ctrl</kbd>+<kbd>[</kbd> enters the Escape(`0x1b`) character. I thinked that in Vim, <kbd>Ctrl</kbd>+<kbd>[</kbd> enters the Escape(`0x1b`) character too.

**Comment by rksouthee** [comment]
I see that this was already added in master a few days ago, apologies for opening this issue, I was looking at my fork.

**Comment by malxau** [comment]
Haha never trust git timestamps!  I just pushed this fix this morning.

(I only get to work on this project on weekends, and some of the git timestamps are pure fiction just to make my contribution graph look a little more consistent.)
