### ISSUE TITLE
Yedit 20201102  ...  some bugs.

### ISSUE THREAD

**Issue by Gavin-Holt** [malxau/yori#64]
Hi,

Yedit is really pretty and nice to use, but I have found some bugs.

1. If the cursor is in col1, then enter duplicates the whole line.

2. The following CTRL keys don't work in the new release:

    CTRL+N
    CTRL+O
    CTRL+S
    CTRL+Q
    CTRL+G

3. For a none empty file, delete at EOF causes a full crash.

4. Not a bug but - could we have a command line switch to unset Traditional navigation?

5. I also have a question about undo granularity.

	Remembering I'm not a coder: I suspect there is an undo stack and some actions chunk the undo actions into sets -
	cf. https://www.scintilla.org/ScintillaDoc.html#SCI_BEGINUNDOACTION.
        i) Could you point me to the section of your code where I can learn which actions delimit the chunks?
        ii) Is there any code to restore the cursor/selection as part of the process?

Kind Regards Gavin Holt

**Comment by malxau** [comment]
Thanks for letting me know.  I meant to reach out to you to try out this build - the undo changes were huge and I knew they'd introduce bugs.

I pushed fixes for the first four issues.

For 5i, see YoriWinMultilineEditGetUndoRecordForOperation at https://github.com/malxau/yori/blob/master/libwin/mledit.c#L1358 . The top section of this function (currently line 1381-1402) is trying to determine if an insert immediately follows a previous insert, or a delete extends a previous delete (in either direction) or if an overwrite extends a previous overwrite.  I could imagine some simple timestamp here too, to indicate that if the new change happens more than (say) 10 seconds after the previous change that it should be considered a new change.  It'll always be a heuristic (ie., imperfect) though.

For 5ii, that should be done today.  The code is in YoriWinMultilineEditApplyUndoRecord.  Each operation type explicitly sets the cursor to something.  The one I'm least happy with is currently the cursor is set to the beginning of an overwrite range, which seems a little unnatural - both of the others seem to do approximately what I'd expect.  What behavior are you seeing here and what behavior would you like to see?

**Comment by malxau** [comment]
I pushed new binaries if you'd like to try out the latest round of fixes.  The current stable build is approaching its 120 day warning limit, so I'd like to release a new stable build soon, and all of the new/untested changes recently are in edit.

**Comment by Gavin-Holt** [comment]
Hi,

Yedit 20201105 [1] - solves all the issues I have found (many thanks for the -m option)

I plan to sit down and compare the "undo granularity" of Yedit with some common windows editors (perhaps using autohotkey scripts) and will report back.

Once again thanks for delivering something many users have wanted for a long time - a beautiful/simple console based editor. 
Yedit is a now part of my daily "software trinity" (Editor-Filemanager-Menu)  with eXtreme[2] and kixtart[3].  

I think the editor is fully usable and at <100kb is a fine achievement. There is a definite niche for instant loading "simple" editors to make quick adjustments - we all have big editors for complex sessions. Limiting any additional functionality, to keep it simple will be a matter of taste and it's your opinion that counts most! 

Having spent more time than I should playing with editors I suspect the most requested additions would be soft wrapping,  auto-indenting with smart home, file reload and file execute. (There may be calls for multiple cursors, syntax highlighting and spellchecking - but these are really in the realm of the big editors).

Kind Regards Gavin Holt 

[1] http://malsmith.net/download?obj=yori/latest-daily/yori-typical-win32.cab
[2] http://textmode.netne.net/Extreme.html 
[3] http://kixtart.org
