### ISSUE TITLE
Inconsistent behavior is between the general file path and the URL style file path

### ISSUE THREAD

**Issue by codehz** [malxau/yori#68]
`dir file://C:/Users` will list only `<DIR> Users`
but `dir C:\Users` will list all files on C:\Users folder

**Comment by malxau** [comment]
Thanks for letting me know.  I pushed a fix for this as commit c2e766adb2740bc8042d016888ddd3474d70b6e5.  It looks like it was broken since this code was first put there (before it was in git.)

**Comment by malxau** [comment]
This should be fixed in 1.50, released today.  Please let me know if there are further related issues.
