### ISSUE TITLE
COPY and MOVE utilities do not overwrite read-only files

### ISSUE THREAD

**Issue by aleaksunder** [malxau/yori#78]
This is correct behavior but there is no option to overwrite such files, at least now I can not see any of it... I have not tested with Hidden and System attributes, but maybe a couple of additional switches to COPY and MOVE will be useful:
```
-oR to overwrite Read-Only
-oH to overwrite Hidden
-oS to overwrite System
```
Only trick here that I see is what to do if you specify only `-oR` switch but file has Read-Only and Hidden attributes or System as well... maybe it will be simplier to make only one option:
```
-o to overwrite everything
```

**Comment by malxau** [comment]
Yori has generally just ignored these attributes on the basis that they're legacy from a time when these things couldn't be described with ACLs.  I updated copy, move and co to overwrite these.

**Comment by aleaksunder** [comment]
Excelent! Thanks a lot!
