### ISSUE TITLE
MOVE and ERASE do not raise ERRORLEVEL when file is locked with another process

### ISSUE THREAD

**Issue by aleaksunder** [malxau/yori#86]
Hi!

Another finding... let's create `C:\temp\raiser.txt` and lock it with following:
```
CMD> notepad.exe > "C:\temp\raiser.txt"
```
so this file will be locked until `notepad.exe` will be closed... and now try to move or erase this file:
```
CMD> "ymove.exe" "C:\temp\raiser.txt" "C:\temp\deraiser.txt"
CMD> ECHO.!ERRORLEVEL!
0
```
`ymove.exe  "C:\temp" "C:\tempNew"` with locked file in `C:\temp` leads to the same... and almost same thing with `ERASE`:
```
CMD> "yerase.exe" "C:\temp\raiser.txt"
erase: delete of \\?\C:\temp\raiser.txt failed: <<here goes localized error message>>
CMD> ECHO.!ERRORLEVEL!
0
```
at least error message is shown, but `ERRORLEVEL` becomes `0`

**Comment by aleaksunder** [comment]
And by the way when `COPY` is used with `-p` switch to preserve existing files and it comes in situation where no files can be copied due to all files are already exist and all is fine... but `COPY` raises ERRORLEVEL and as for me this is obviously not an error

**Comment by malxau** [comment]
Is it consistent to say that `MKDIR` should fail if the object exists but `COPY -P` should succeed if the object exists?  In both cases the outcome is the same: the tool has performed no processing and the system has achieved its requested state.

**Comment by aleaksunder** [comment]
Yes, I can agree that in case of `MKDIR` and `COPY -P` the result is the same that it was expected... the thing with `COPY -P` is that I need to check the ERRORLEVEL in script after `COPY -P` to be sure that all was copied without any errors, but ERRORLEVEL was raised due to nothing to copy reason, and script fails since it need to check that all is fine before continue, and all is fine in real, but there is an error... and there is no way to check that all is fine in that case! In `MKDIR` scenario we can check the directory exist but with recursive `COPY -S -P` we can not

**Comment by malxau** [comment]
The thing I'm trying to point out though is that success means different things to different people, and I can't write a single-bit return value that is correct for everyone.  Creating an existing directory or deleting a nonexistent file could easily be considered success in the right context.

Because all of these tools allow for an arbitrary number of arguments, each of which contain wildcards, they can be asked to do an arbitrarily large number of things.  The pattern I've been following is that if they successfully do any one thing, they were successful.  But it's easy to imagine cases where this is not success in a particular application, and this comment is about a case where they didn't do anything which might be successful in a particular application.

I think the focus here needs to switch to stderr parsing, and I should be trying to ensure that stderr contains accurate output for issues that were encountered.  This means instead of a single bit of information there's an arbitrary number of errors that can be returned to express the arbitrary number of conditions which the commands might encounter.

**Comment by aleaksunder** [comment]
This is tough enough even to discuss =) Since you are right, there is too many different people with too different point of view! The situation becomes more difficult due to already existing script and there is no way something can be changed in principle without hurting somebody so basically parsing `stderr` is only option we have in such situation... So wrote CMD-variant that way:
```
    @FOR /F "usebackq tokens=*"delims^=^ eol^= %%E IN (

        `""C:\yori\ycopy.exe" -s -p "C:\temp\2\*" "C:\temp\3" 2>&1 1>nul"`

    ) DO @(

        @IF NOT "[ %%~E ]" == "[ copy: no matching files found ]" @(

            @ECHO.  Can not copy directory contents: "C:\temp\2" to "C:\temp\3"
            @GOTO :label_exit

        )

    )
```
despite as for me it is horroble, awful and terrible =) This seems pretty obvious and straightforward... The only thing I can not understand how to do this with Yori shell, so simply how to write Yori script `.ys1` which will parse only STDERR during command execution?

**Comment by aleaksunder** [comment]
Anyway this gone far away from the original subject!

I've hit another issue with `ymove.exe`... this works from Yori:
```
YORI > move C:\temp\file D:\file
```
and this is not from CMD:
```
CMD > ymove.exe C:\temp\file D:\file
```
just shows error message: `MoveFile failed: The system cannot move the file to another drive.`

I think the original `MOVE and ERASE do not raise ERRORLEVEL when file is locked with another process` and this `ymove.exe to another drive` can be fixed without any consequences for others

**Comment by malxau** [comment]
Were these the same version of ymove?  There was a nasty bug introduced in 414c9827417c40e0d2f56a48fc37ed9ec3cc00be and fixed in 2b81159b288cb435327e3c3e232424b9c4d4d5ed which meant it didn't specify MOVEFILE_COPY_ALLOWED correctly, which is needed for cross drive moves.

**Comment by aleaksunder** [comment]
Just done some tests with current source... now `ymove.exe` works with different drive letters.

And in a nutshell after `CMD> notepad.exe > "C:\temp\raiser.txt"`:
```
CMD> ymove.exe "C:\temp\raiser.txt" "C:\temp\deraiser.txt"
CMD> ECHO %ERRORLEVEL%
1
```
works as expected!

```
CMD> yerase.exe "C:\temp\raiser.txt"
CMD> ECHO %ERRORLEVEL%
0
```
should be 1

**Comment by aleaksunder** [comment]
And I accidentaly got in to some "weird magic unbelievable" one thing:
I'm pretty sure that there was no "D:\temp2" directory and basically there was not even a chance this directory exist, since that was a typo... I've did some tests and accidentialy enter this:
```
CMD > ymove.exe D:\temp2\temp1
```
this is not it was supposed to be but this was executed and the answer was:
```
Enumerate of D:\temp2 failed: Invalid folder name
```
after this I've executed:
```
CMD> ECHO %ERRORLEVEL%
0
```
and after that I've realised it was a typo but when I came back to it lately and tried to reproduce... basically I can not since when I enter it again:
```
CMD > ymove.exe D:\temp2\temp1
```
the answer was:
```
File or directory not found: D:\temp2\temp1
```
and ERRORLEVEL raised to 1

I'm not even trying to understand what it was since there was no `D:\temp2` directory at all... finally I've looked at source of `MOVE` and it seems to me that in situation when it fails to enumerate a folder it does not raise an ERRORLEVEL
Just want to mention it... I understand that this is "weird magic unbelievable" stuff at all and there nothing we can do since I am not able even to reproduce it =)

**Comment by aleaksunder** [comment]
Perfect!
