### ISSUE TITLE
yedit support byte order mark

### ISSUE THREAD

**Issue by tenox7** [malxau/yori#90]
Since Yedit supports UTF encoding it would be nice if it also supported https://en.wikipedia.org/wiki/Byte_order_mark a lot of UTF16 encoded files in Windows start with U+FEFF BOM character.

**Comment by malxau** [comment]
I added some limited support for this in commit 74ddb11a955e9f0f57db77588e9c530e7d8662f7 .  Note that this can only work when a UTF-16 BOM is present; if not, it is interpreted as UTF-8.  I really don't want to get into the IsTextUnicode() quagmire of heuristically trying to distinguish text which could be either.

**Comment by tenox7** [comment]
Thank you!!!!!!!!!!

**Comment by malxau** [comment]
This should be fixed in 1.50, released today.  Please let me know if there are further related issues.
