### ISSUE TITLE
Yori doesn't handle PROMPT correctly? 

### ISSUE THREAD

**Issue by bgianfo** [malxau/yori#95]
I have the following prompt: 

```
PROMPT=[$E[92m$T$H$H$H$E[39m ~ $E[95m$P$E[39m]$+$_$$
```

In normal cmd it looks like: 
![image](https://user-images.githubusercontent.com/1212/114784345-f6870680-9d2f-11eb-81d1-b8d158b890d0.png)

In yori it looks like:

![image](https://user-images.githubusercontent.com/1212/114784384-0999d680-9d30-11eb-99d1-94b0ed60d824.png)

Prompt config is documented here: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/prompt

**Comment by malxau** [comment]
Yori uses a different environment variable for prompt, which is documented at http://www.malsmith.net/yori/guide/#env_yoriprompt

The issue with trying to use the same variable for both is that CMD will not understand any extensions that Yori tries to add, and this is an area that I wanted to do substantially better than CMD.  Yori's prompts can include backquotes to capture arbitrary output of processes, and will expand environment variables.  CMD can't do these things, so trying to use one variable would result in garbage from CMD.

**Comment by bgianfo** [comment]
Fair enough, thanks for the link to the docs!
