### ISSUE TITLE
yhash not supported in Windows XP

### ISSUE THREAD

**Issue by zoomosis** [malxau/yori#98]
Using yhash.exe in Windows XP SP3 results in the error message "hash: operating system support not present".

Obviously XP is now "vintage" and unsupported, though if you're building Yori with MSVC 2.0 I suspect you'd like to have Yori's compatibility to go all the way back to Windows NT 3.1. So perhaps yhash should supply its own hashing code rather than relying on a modern Windows API call.

Also, "yhash -?" should document that SHA1 is the default algorithm if none is specified.

Thanks!

**Comment by tumagonx** [comment]
why not using Wincrypt? I think XP SP3 with CSP update capable of SHA-512 (not bad)

**Comment by zoomosis** [comment]
With a couple of syntax changes to accommodate Open Watcom 2.0, I was able to build and run Microsoft's own example code for calculating MD5 checksums:

https://docs.microsoft.com/en-us/windows/win32/seccrypto/example-c-program--creating-an-md-5-hash-from-file-content

The binary seems to run fine under XP SP3 and NT 4.0 SP6.

NT 3.51 is too old and complains that the CryptAcquireContextA procedure is missing from ADVAPI32.DLL.

If you're using MSVC 2.0 then I suspect wincrypt.h is missing from the headers but maybe that's not too difficult to work around and conceivably a lot easier than wrestling with BCrypt.

(Obviously MD5 isn't perfect, but it's still useful.)

**Comment by malxau** [comment]
Thanks, I didn't know these functions existed.  Agree that if there's an option that exists on more versions, Yori should use it.

It doesn't matter much about working around missing header defines or exports.  That already needed to exist for the Vista+ version anyway, so it's just about changing from one set of functions to another.

I have changes pending for this which I'll push soon.  As you've already noted, MD5 and SHA1 exists on NT4+.  SHA256/384/512 exists on XP SP3 and 2003 SP2.  There's some hacking around requesting the "enhanced" provider which provides those hashes, but it's not too serious.
